AddonId: DescriptionFixer_b86cf867-0519-49ef-b7b7-386b6a1e2830
Packages:
  - Version: 1.0
    RequiredApiVersion: 6.12.0
    ReleaseDate: 2025-08-11
    PackageUrl: https://github.com/azuravian/playnite-DescriptionFixer/releases/download/v1.0/DescriptionFixer_b86cf867-0519-49ef-b7b7-386b6a1e2830_1_0.pext
    Changelog:
      - Initial Release
  - Version: 1.1
    RequiredApiVersion: 6.12.0
    ReleaseDate: 2025-08-12
    PackageUrl: https://github.com/azuravian/playnite-DescriptionFixer/releases/download/v1.1/DescriptionFixer_b86cf867-0519-49ef-b7b7-386b6a1e2830_1_1.pext
    Changelog:
      - Added support for converting webp images to png.